baseURL = 'http://taphill.com/'
languageCode = 'en-us'
title = 'Taylor Phillips'

[Params]
  css = [
    "stylesheets/reset.css",
    "stylesheets/base.css",
    "stylesheets/utilities.css",
    "stylesheets/blocks.css"
  ]

[markup]
  [markup.highlight]
    style = 'perldoc'
